# Installing packages individually ( Slower Process )

- hosts: webservers
  sudo: yes
  remote_user: root
  
  tasks:
   - name: Installing Git
     apt:
       name: git
       update_cache: yes
   - name: Installing nginx
     apt:
       name: nginx
       update_cache: yes
   - name: Installing memcached
     apt:
       name: memcached
       update_cache: yes