---
- hosts: webservers
  sudo: yes
  vars:
    http_port: 80
    doc_root: /var/www/html/

  vars_prompt:
    - name: username
      prompt: What is your name ? What is your hobby ? what is your fav color?

  tasks:
  - name: Ensure that Apache is installed
    yum: name=httpd state=present
    when: ansible_os_family == "RedHat"

  - name: Start Apache Services
    service: name=httpd enabled=yes state=started

  - name: Copy site file for my applicationwith packages
    template: src=templates/index.j2 dest={{ doc_root }}/index.html



