---
#final yaml file
- hosts: webservers
  sudo: yes

  vars:
    http_port: 80
    doc_root: /var/www/html/
    max_clients: 5
    doc_dir: /ansible/

  vars_prompt:
    - name: username
      prompt: What is your name ? What is your hobby ? what is your fav color?

  tasks:
  - name: Ensure that Apache is installed
    yum: name=httpd state=present
    when: ansible_os_family == "RedHat"

  - name: Start Apache Services
    service: name=httpd enabled=yes state=started

  - name: Deploy configuration File
    template: src=templates/httpd.j2 dest=/etc/httpd/conf/httpd.conf
    notify:
      - Restart Apache

  handlers:
     - name: Restart Apache
       service: name=httpd state=restarted





