---
# use of register variable


- hosts: webservers
  sudo: yes
  remote_user: root

  tasks:
  - name: Ansible register variable basic example
    shell: "find *.txt"
    args:
      chdir: "/home/vagrant/"
    register: find_output

  - debug:
      var: find_output
