---
# this is a playbook for the users to be created using with_swequence


 - hosts: webservers
   sudo: yes

   tasks:
    - name: Create Users using with_sequence 
      user:
        name: "{{ item }}"
        state: present
      with_sequence: start=01 end=10 format=Khurram%02x
