---
# this is the playbook to remove the users 

 - hosts: webservers
   sudo: yes
   remote_user: root

   tasks:
    - name: Create Users using with_sequence 
      user:
        name: "{{ item }}"
        state: absent
      with_sequence: start=01 end=10 format=Khurram%02x
